language: cpp

os:
    - linux
    - osx

sudo:
    - true

matrix:
    include:
        - os: linux
          env: QT_BASE=48 COMPILER=g++-4.4 CMAKE_BUILD_TYPE=Debug
          compiler: gcc

        - os: linux
          env: QT_BASE=48 COMPILER=clang++
          compiler: clang

        - os: linux
          env: QT_BASE=57 COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Debug
          compiler: gcc

        - os: linux
          env: QT_BASE=57 COMPILER=clang++ CMAKE_BUILD_TYPE=Debug
          compiler: clang

        - os: osx
          env: CMAKE_BUILD_TYPE=Debug
          compiler: clang

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test &&
        if [ "{QT_BASE}" = "57" ]; then
          sudo apt-add-repository -y ppa:beineri/opt-qt57-trusty &&
          sudo apt-get -qq update &&
          if [ "{COMPILER}" = "g++-4.9" ]; then
            sudo apt-get -qq install g++-4.9 gcc-4.9 qt57tools qt57base qt57webchannel qt57webengine qt57websockets &&
            export CXX="g++-4.9" &&
            export CC="gcc-4.9"
            ;
          else
            sudo apt-get -qq install qt57tools qt57base qt57webchannel qt57webengine qt57websockets &&
            export CXX="clang++" &&
            export CC="clang"
            ;
          fi
          ;
        else
          sudo apt-get -qq update &&
          if [ "{COMPILER}" = "g++-4.4" ]; then
            sudo apt-get -qq install g++-4.4 gcc-4.4 &&
            export CXX="g++-4.4" &&
            export CC="gcc-4.4"
            ;
          else
            export CXX="clang++" &&
            export CC="clang"
            ;
          fi
          ;
        fi
        ;
      else
        brew update &&
        brew unlink cmake &&
        brew install cmake &&
        brew install qt5 &&
        chmod -R 755 /usr/local/opt/qt5/*
        ;
      fi

before_script:
    - mkdir build
    - cd build
    - cmake --version
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..

script: make && make check
